#!/bin/sh
set -e

err() {
  echo "[ERROR] $1" >&2
  exit 1
}

smitty() {
  echo; echo
  echo "[INFO] $@"
  $@
}

git remote show upstream &> /dev/null || smitty git remote add upstream https://github.com/jumanjihouse/dropbox.git

smitty bundle update 2> /dev/null || smitty bundle install --path=~/.bundle
